name: symmetric_difference
description: symmetric defference library
version: 2.0.0
repository: https://github.com/ScorlyFly/Symmetric_difference

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

license: MIT
